id: state_of_js
slug: state_of_js
hashtag: StateOfJS
name: State of JavaScript
domain: stateofjs.com

imageUrl: https://assets.devographics.com/surveys/state_of_js.png
faviconUrl: https://assets.devographics.com/surveys/state_of_js-favicon.svg

emailOctopus:
  listId: 463dc2a9-b2ff-11e8-a3c9-06b79b628af2
  submitUrl: https://eomail3.com/form/75eba896-47ef-11ef-b09f-cbebfc926a4c

partners:
  - name: Google Chrome
    id: google_chrome
    url: https://google.com
    imageUrl: https://assets.devographics.com/sponsors/google.png
  - name: TokyoDev
    id: tokyodev
    url: https://www.tokyodev.com/
    imageUrl: https://assets.devographics.com/sponsors/tokyodev.svg
  - name: Frontend Masters
    id: frontendmasters
    url: https://frontendmasters.com/?utm_source=stateofjs&utm_medium=website&utm_campaign=stateofjs2023
    imageUrl: https://devographics.github.io/surveys/state_of_css/css2023/images/sponsors/frontend-masters-dark.png
  - name: GitNation
    id: gitnation
    url: https://gitnation.com/?utm_source=Influencer&utm_medium=stateofjs
    imageUrl: https://assets.devographics.com/sponsors/GitNation-orange.svg
