id: graphql2022
surveyId: graphql2022
startedAt: June 15, 2022
endedAt: July 15, 2022
shareUrl: https://stateofgraphql.com
questionsUrl: https://survey.devographics.com/survey/state-of-graphql/2022
resultsUrl: https://2022.stateofgraphql.com/
year: 2022
status: 3 # preview/open/closed/hidden
imageUrl: https://devographics.github.io/surveys/state_of_graphql/2022/images/graphql2022.png
faviconUrl: https://devographics.github.io/surveys/state_of_graphql/2022/images/graphql2022-favicon.svg
socialImageUrl: https://devographics.github.io/surveys/state_of_graphql/2022/images/graphql2022-og.png

colors:
  primary: "#F999D3"
  secondary: "#5C63E0"
  text: "#FFF6E6"
  background: "#263342"
  backgroundSecondary: "#2C4461"

credits:
  - id: eric_burel
    role: back_end_developement
  - id: christopher_kirk_nielsen
    role: logo_design
  - id: praveen_durairaju
    role: survey_design
  - id: benjie_gillam
    role: survey_design
  - id: uri_goldshtein
    role: survey_design
  - id: michael_hayes
    role: survey_design
  - id: charly_poly
    role: survey_design
  - id: phil_prasek
    role: survey_design
  - id: laurin_quast
    role: survey_design
  - id: john_p_vajda
    role: survey_design

partners:
  - name: Nijibox
    id: nijibox
    url: https://www.nijibox.jp/
    imageUrl: https://devographics.github.io/surveys/state_of_graphql/2022/images/sponsors/nijibox.svg

sponsors:
  - name: The Guild
    id: the_guild
    url: https://www.the-guild.dev/
    imageUrl: https://devographics.github.io/surveys/state_of_graphql/2022/images/sponsors/the-guild-full-white-logo.svg
  - name: Nhost
    id: nhost
    url: https://nhost.io/
    imageUrl: https://devographics.github.io/surveys/state_of_graphql/2022/images/sponsors/nhost-logo-white.svg
  - name: Apollo
    id: apollo
    url: https://www.apollographql.com/
    imageUrl: https://devographics.github.io/surveys/state_of_graphql/2022/images/sponsors/apollo-graphql-logo.svg
  - name: GraphQL.wtf
    id: graphql_wtf
    url: https://graphql.wtf/
    imageUrl: https://devographics.github.io/surveys/state_of_graphql/2022/images/sponsors/graphql-wtf-pink-white.svg
  - name: Grafbase
    id: grafbase
    url: https://grafbase.com/
    imageUrl: https://devographics.github.io/surveys/state_of_graphql/2022/images/sponsors/grafbase-white-logo-w-text.svg
  - name: Hasura
    id: hasura
    url: https://hasura.io/
    imageUrl: https://devographics.github.io/surveys/state_of_graphql/2022/images/sponsors/hasura-logo-primary-light.svg
  # - name: Frontend Masters
  #   id: frontendmasters
  #   url: https://frontendmasters.com/
  #   imageUrl: https://devographics.github.io/surveys/state_of_graphql/2022/images/sponsors/frontend-masters-dark.png
