id: react2023 # used as first part of field names
startedAt: October 27, 2023
endedAt: November 15, 2023
questionsUrl: https://survey.devographics.com/survey/state-of-react/2023
feedbackUrl: https://github.com/Devographics/surveys/issues/85
# resultsUrl: https://2023.stateofcss.com/
year: 2023
status: 3 # preview/open/closed/hidden
# imageUrl: https://static.devographics.com/stateofcss/2021/images/stateofcss2021.png
# imageUrl: https://devographics.github.io/surveys/state_of_css/css2023/images/css2023.png
# faviconUrl: https://devographics.github.io/surveys/state_of_css/css2023/images/css2023-favicon.svg
# socialImageUrl: https://devographics.github.io/surveys/state_of_css/css2023/images/css2023-og.png

enableReadingList: true
enableChartSponsorships: false
enableSkip: true

colors:
  primary: "#61DAFB"
  secondary: "#9C7FF0"
  text: "#CDF4FF"
  background: "#242829"
  backgroundSecondary: "#566063"

# credits:
credits:
  - id: mark_erikson
    role: survey_design
  - id: lenz_weber_tronic
    role: survey_design
  - id: sebastien_lorber
    role: survey_design
  - id: lee_robinson
    role: survey_design
  - id: filip_tammergard
    role: survey_design
  # - id: christopher_kirk_nielsen
  #   role: logo_design

faq:
  - how_long_will_survey_take_react2023
  - who_should_take_survey_react2023
  - survey_goals_react2023
  - data_used_react2023
  - results_released_react2023
  - team
  - survey_design_react2023
  # - questions_required
  - learn_more_react2023

tags:
  - css
# sponsors:
#   - name: Frontend Masters
#     id: frontendmasters
#     url: https://frontendmasters.com/?utm_source=stateofcss&utm_medium=website&utm_campaign=stateofcss2022
#     imageUrl: https://devographics.github.io/surveys/state_of_css/css2022/images/sponsors/frontend-masters-dark.png
#   # - name: Polypane
#   #   id: polypane
#   #   url: https://polypane.app/
#   #   imageUrl: https://devographics.github.io/surveys/state_of_css/css2022/images/sponsors/polypane.png
#   - name: Google Chrome
#     id: google_chrome
#     url: https://www.google.com/chrome/?utm_source=stateofcss&utm_medium=website&utm_campaign=stateofcss2022
#     imageUrl: https://devographics.github.io/surveys/state_of_css/css2022/images/sponsors/google.png
#   # - name: Nijibox
#   #   id: nijibox
#   #   url: https://www.nijibox.jp/?utm_source=stateofcss&utm_medium=website&utm_campaign=stateofcss2022
#   #   imageUrl: https://devographics.github.io/surveys/state_of_css/css2022/images/sponsors/nijibox.svg
#   - name: RenderATL
#     id: renderatl
#     url: https://www.renderatl.com/?utm_source=stateofcss&utm_medium=website&utm_campaign=stateofcss2022
#     imageUrl: https://devographics.github.io/surveys/state_of_css/css2022/images/sponsors/renderatl.png

sources:
  - id: "state_of_js_survey"
  - id: "twitter"
  - id: "google"
  - id: "youtube"
  - id: "fireship"
  - id: "angular_community"
  - id: "js_weekly"
  - id: "reddit"
  - id: "scrimba"
  - id: "linkedin"
  - id: "work"
  - id: "word_of_mouth"
  - id: "duckduckgo"
  - id: "slack"
  - id: "discord"
  - id: "codrops"
  - id: "microsoft_teams"
  - id: "devto"
  - id: "state_of_css_survey"
  - id: "mastodon"
  - id: "midudev"
  - id: "web_standards_ru"
  - id: "bytes"
  - id: "facebook"
  - id: "telegram"
  - id: "vue_community"
  - id: "theo_browne"
  - id: "brave"
  - id: "kevin_j_powell"
  - id: "state_of_frontend"
  - id: "elm_community"
  - id: "james_q_quick"
  - id: "zero_to_mastery"
  - id: "front_end_front"
  - id: "github"
  - id: "svelte_community"
  - id: "bing"
  - id: "twitch"
  - id: "coding_garden"
  - id: "kode24"
  - id: "rich_harris"
  - id: "frontend_focus"
  - id: "jser"
  - id: "ryan_carniato"
  - id: "changelog"
  - id: "state_of_purescript"
  - id: "eleventy"
  - id: "hn"
  - id: "instagram"
