id: react2025
feedbackAt: August 1, 2025
startedAt: September 1, 2025
endedAt: October 1, 2025
releasedAt: November 1, 2025
questionsUrl: https://survey.devographics.com/survey/state-of-react/2025
feedbackUrl: https://github.com/Devographics/surveys/issues/262
resultsUrl: https://2025.stateofreact.com/
year: 2025
status: 2 # preview/open/closed/hidden
resultsStatus: 1 # hidden/preview/published

# imageUrl: https://static.devographics.com/stateofcss/2021/images/stateofcss2021.png
# imageUrl: https://devographics.github.io/surveys/state_of_css/css2023/images/css2023.png
# faviconUrl: https://devographics.github.io/surveys/state_of_css/css2023/images/css2023-favicon.svg
# socialImageUrl: https://devographics.github.io/surveys/state_of_css/css2023/images/css2023-og.png

enableGoal: true
enableReadingList: true
enableScore: true
enableSkip: true

responsesGoal: 10000

tshirt:
  images: ["react2023-tshirt.webp"]
  url: https://cottonbureau.com/p/NV42G5/shirt/react-atom
  price: 32
  designerUrl: https://chriskirknielsen.com/

colors:
  primary: "#61DAFB"
  secondary: "#9C7FF0"
  text: "#CDF4FF"
  background: "#242829"
  backgroundSecondary: "#566063"

# credits:
credits:
  # - id: mark_erikson
  #   role: survey_design
  # - id: lenz_weber_tronic
  #   role: survey_design
  # - id: sebastien_lorber
  #   role: survey_design
  # - id: lee_robinson
  #   role: survey_design
  # - id: filip_tammergard
  #   role: survey_design
  - id: christopher_kirk_nielsen
    role: logo_design

sponsors:
  # - name: Polypane
  #   id: polypane
  #   url: https://polypane.app/
  #   imageUrl: https://devographics.github.io/surveys/state_of_css/css2023/images/sponsors/polypane.png
  - name: Google Chrome
    id: google_chrome
    url: https://www.google.com/chrome/?utm_source=stateofjs&utm_medium=website&utm_campaign=stateofjs2024
    imageUrl: https://assets.devographics.com/sponsors/google.png
  - name: TokyoDev
    id: tokyodev
    url: https://www.tokyodev.com/?utm_source=stateofjs&utm_medium=website&utm_campaign=stateofjs2024
    imageUrl: https://assets.devographics.com/sponsors/tokyodev.svg
  - name: Frontend Masters
    id: frontendmasters
    url: https://frontendmasters.com/?utm_source=stateofjs&utm_medium=website&utm_campaign=stateofjs2024
    imageUrl: https://devographics.github.io/surveys/state_of_css/css2023/images/sponsors/frontend-masters-dark.png
  # - name: GitNation
  #   id: gitnation
  #   url: https://gitnation.com/?utm_source=stateofjs&utm_medium=website&utm_campaign=stateofjs2024
  #   imageUrl: https://assets.devographics.com/sponsors/GitNation-orange.svg
  - name: Algolia
    id: algolia
    url: https://www.algolia.com/?utm_source=stateofcss&utm_medium=website&utm_campaign=css2025
    imageUrl: https://assets.devographics.com/sponsors/algolia-logo-white.svg
  - name: Storyblok
    id: storyblok
    url: https://www.storyblok.com/?utm_source=stateofcss&utm_medium=website&utm_campaign=css2025
    imageUrl: https://assets.devographics.com/sponsors/storyblok-light.svg
  # - name: Jetbrains
  #   id: jetbrains
  #   url: https://www.jetbrains.com/?utm_source=stateofcss&utm_medium=website&utm_campaign=css2025
  #   imageUrl: https://assets.devographics.com/sponsors/jetbrains.svg
  - name: WebStorm
    id: webstorm
    url: https://www.jetbrains.com/webstorm/?utm_source=stateofcss&utm_medium=website&utm_campaign=css2025
    imageUrl: https://assets.devographics.com/sponsors/webstorm.svg

faq:
  - how_long_will_survey_take_react
  - who_should_take_survey_react
  - survey_goals_react
  - data_used_react
  - results_released_react2025
  - team
  - survey_design_react2025
  # - questions_required
  # - learn_more_react2024

tags:
  - react

sources:
  - id: "state_of_js_survey"
  - id: "twitter"
  - id: "google"
  - id: "youtube"
  - id: "fireship"
  - id: "angular_community"
  - id: "js_weekly"
  - id: "reddit"
  - id: "scrimba"
  - id: "linkedin"
  - id: "work"
  - id: "word_of_mouth"
  - id: "duckduckgo"
  - id: "slack"
  - id: "discord"
  - id: "codrops"
  - id: "microsoft_teams"
  - id: "devto"
  - id: "state_of_css_survey"
  - id: "mastodon"
  - id: "midudev"
  - id: "web_standards_ru"
  - id: "bytes"
  - id: "facebook"
  - id: "telegram"
  - id: "vue_community"
  - id: "theo_browne"
  - id: "brave"
  - id: "kevin_j_powell"
  - id: "state_of_frontend"
  - id: "elm_community"
  - id: "james_q_quick"
  - id: "zero_to_mastery"
  - id: "front_end_front"
  - id: "github"
  - id: "svelte_community"
  - id: "bing"
  - id: "twitch"
  - id: "coding_garden"
  - id: "kode24"
  - id: "rich_harris"
  - id: "frontend_focus"
  - id: "jser"
  - id: "ryan_carniato"
  - id: "changelog"
  - id: "state_of_purescript"
  - id: "eleventy"
  - id: "hn"
  - id: "instagram"
