---
slug: js2022
surveyId: js2022
context: state_of_js
topic: JavaScript
createdAt: November 1, 2022
prettySlug: state-of-js
hashtag: StateOfJS
shareUrl: https://stateofjs.com
# resultsUrl: https://2022.stateofjs.com/
name: "State of JavaScript"
year: 2022
status: 1 # preview/open/closed/hidden
imageUrl: "js2022@075x.png"
domain: stateofjs.com
bgColor: rgb(34, 36, 41)
textColor: rgb(224, 228, 228)
linkColor: rgb(65, 199, 199)
hoverColor: rgb(254, 106, 106)
tags: [js]
credits:
  - id: shawn_wang
    role: survey_design
  - id: mark_erikson
    role: survey_design
faq:
  - data_used_js2022
  # - survey_design_js2022
  - results_released_js2022
  - team
  - questions_required
  - learn_more_js2022

colors: 
  primary: rgb(71, 207, 237)
  secondary: "#8D4CA8"
  text: rgb(255, 246, 230)
  background: rgb(39, 35, 37)
  backgroundSecondary: rgb(48, 52, 53)
  