id: html2025 # used as first part of field names
feedbackAt: June 15, 2025
startedAt: July 15, 2025
endedAt: August 31, 2025
releasedAt: September 15, 2025
questionsUrl: https://survey.devographics.com/survey/state-of-html/2025
feedbackUrl: https://github.com/Devographics/surveys/issues/253
resultsUrl: https://2025.stateofhtml.com/
year: 2025
status: 3 # preview/open/closed/hidden
resultsStatus: 3 # hidden/preview/published
# imageUrl: https://static.devographics.com/stateofcss/2021/images/stateofcss2021.png
imageUrl: https://assets.devographics.com/surveys/html2025.png
faviconUrl: https://assets.devographics.com/surveys/html2025-favicon.svg
socialImageUrl: https://assets.devographics.com/surveys/html2025-og.png
hashtag: StateOfHTML

enableChartSponsorships: false
enableReadingList: true
enableSkip: true
enableScore: true

tshirt:
  images: ["html2023-tshirt.webp"]
  url: https://cottonbureau.com/p/8U4SGF/shirt/html-retro-vhs
  price: 32
  designerUrl: https://chriskirknielsen.com/

colors:
  primary: "#FDE86E"
  secondary: "#219BD5"
  text: "#FFE7BD"
  background: "#301639"
  backgroundSecondary: "#45344B"

credits:
  - id: lea_verou
    role: survey_design
  - id: christopher_kirk_nielsen
    role: logo_design

faq:
  - how_long_will_survey_take_html
  - who_should_take_survey_html
  - survey_goals_html
  - data_used_html
  - results_released_html2025
  - team
  - survey_design_html2025
  # - questions_required
  # - learn_more_html2025

tags:
  - css

# partners:
#   - name: Nijibox
#     id: nijibox
#     url: https://www.nijibox.jp/
#     imageUrl: https://devographics.github.io/surveys/state_of_css/css2022/images/sponsors/nijibox.svg

sponsors:
  - name: Google Chrome
    id: google_chrome
    url: https://www.google.com/chrome/?utm_source=stateofcss&utm_medium=website&utm_campaign=css2024
    imageUrl: https://devographics.github.io/surveys/state_of_css/css2024/images/sponsors/google.png
  # - name: Google Chrome
  #   id: google_chrome
  #   url: https://www.google.com/chrome/?utm_source=stateofcss&utm_medium=website&utm_campaign=html2025
  #   imageUrl: https://assets.devographics.com/sponsors/google.png
  - name: TokyoDev
    id: tokyodev
    url: https://www.tokyodev.com/?utm_source=stateofcss&utm_medium=website&utm_campaign=html2025
    imageUrl: https://assets.devographics.com/sponsors/tokyodev.svg
  - name: Frontend Masters
    id: frontendmasters
    url: https://frontendmasters.com/?utm_source=stateofcss&utm_medium=website&utm_campaign=html2025
    imageUrl: https://assets.devographics.com/sponsors/frontend-masters-dark.png
  - name: Algolia
    id: algolia
    url: https://www.algolia.com/?utm_source=stateofcss&utm_medium=website&utm_campaign=html2025
    imageUrl: https://assets.devographics.com/sponsors/algolia-logo-white.svg
  - name: Storyblok
    id: storyblok
    url: https://www.storyblok.com/?utm_source=stateofcss&utm_medium=website&utm_campaign=html2025
    imageUrl: https://assets.devographics.com/sponsors/storyblok-light.svg
  # - name: Jetbrains
  #   id: jetbrains
  #   url: https://www.jetbrains.com/?utm_source=stateofcss&utm_medium=website&utm_campaign=html2025
  #   imageUrl: https://assets.devographics.com/sponsors/jetbrains.svg
  - name: WebStorm
    id: webstorm
    url: https://www.jetbrains.com/webstorm/?utm_source=stateofcss&utm_medium=website&utm_campaign=html2025
    imageUrl: https://assets.devographics.com/sponsors/webstorm.svg

  # - name: GitNation
  #   id: gitnation
  #   url: https://gitnation.com/?utm_source=stateofcss&utm_medium=website&utm_campaign=html2025
  #   imageUrl: https://assets.devographics.com/sponsors/GitNation-orange.svg
  - name: Polypane
    id: polypane
    url: https://polypane.app/?utm_source=stateofcss&utm_medium=website&utm_campaign=html2025
    imageUrl: https://devographics.github.io/surveys/state_of_css/css2023/images/sponsors/polypane.png

sources:
  - id: state_of_js_survey
  - id: kevin_j_powell
  - id: state_of_js_css_survey
  - id: lea_verou
  - id: theo_browne
  - id: state_of_css_survey
  - id: twitter
  - id: youtube
  - id: state_of_html_survey
  - id: google
  - id: hn
  - id: post_survey_share
  - id: work
  - id: mastodon
  - id: sacha_greif
  - id: linkedin
  - id: web_dev
  - id: js_weekly
  - id: codrops
  - id: word_of_mouth
