id: state_of_css
slug: state_of_css
hashtag: StateOfCSS
domain: stateofcss.com
name: State of CSS

imageUrl: https://assets.devographics.com/surveys/state_of_css.png
faviconUrl: https://assets.devographics.com/surveys/state_of_css-favicon.svg

# emailOctopus:
#   listId: ed0386c4-2f55-11e9-a3c9-06b79b628af2
# new list: just use state of js list
emailOctopus:
  listId: 463dc2a9-b2ff-11e8-a3c9-06b79b628af2
  submitUrl: https://eomail3.com/form/e437eeb6-47f1-11ef-8e21-8d1e48e47b5e

partners:
  - name: Nijibox
    id: nijibox
    url: https://www.nijibox.jp/
    imageUrl: https://devographics.github.io/surveys/state_of_graphql/graphql2022/images/sponsors/nijibox.svg
  - name: Google Chrome
    id: google_chrome
    url: https://google.com
    imageUrl: https://devographics.github.io/surveys/state_of_css/css2022/images/sponsors/google.png
