id: css2023 # used as first part of field names
surveyId: css2023 # used as first part of field names
startedAt: June 15, 2023
endedAt: July 15, 2023
questionsUrl: https://survey.devographics.com/survey/state-of-css/2023
resultsUrl: https://2023.stateofcss.com/
year: 2023
status: 3 # preview/open/closed/hidden
resultsStatus: 1 # hidden/preview/published
# imageUrl: https://static.devographics.com/stateofcss/2021/images/stateofcss2021.png
imageUrl: https://devographics.github.io/surveys/state_of_css/css2023/images/css2023.png
faviconUrl: https://devographics.github.io/surveys/state_of_css/css2023/images/css2023-favicon.svg
socialImageUrl: https://devographics.github.io/surveys/state_of_css/css2023/images/css2023-og.png

enableChartSponsorships: false
enableReadingList: true

colors:
  primary: rgb(239, 78, 136)
  secondary: "#3633B7"
  text: rgb(255, 246, 230)
  background: rgb(39, 35, 37)
  backgroundSecondary: rgb(62, 48, 54)

credits:
  - id: chen_hui_jing
    role: survey_design
  - id: christopher_kirk_nielsen
    role: logo_design

faq:
  - how_long_will_survey_take_css2023
  - who_should_take_survey_css
  - survey_goals_css
  - data_used_css
  - results_released_css2023
  - team
  - survey_design_css2023
  # - questions_required
  - learn_more_css2023

tags:
  - css

partners:
  - name: Nijibox
    id: nijibox
    url: https://www.nijibox.jp/
    imageUrl: https://devographics.github.io/surveys/state_of_css/css2022/images/sponsors/nijibox.svg

sponsors:
  - name: Google Chrome
    id: google_chrome
    url: https://www.google.com/chrome/?utm_source=stateofcss&utm_medium=website&utm_campaign=stateofcss2022
    imageUrl: https://devographics.github.io/surveys/state_of_css/css2022/images/sponsors/google.png
  - name: Frontend Masters
    id: frontendmasters
    url: https://frontendmasters.com/?utm_source=stateofcss&utm_medium=website&utm_campaign=stateofcss2022
    imageUrl: https://devographics.github.io/surveys/state_of_css/css2022/images/sponsors/frontend-masters-dark.png
  - name: RenderATL
    id: renderatl
    url: https://www.renderatl.com/?utm_source=stateofcss&utm_medium=website&utm_campaign=stateofcss2022
    imageUrl: https://devographics.github.io/surveys/state_of_css/css2022/images/sponsors/renderatl.png
  - name: Nijibox
    id: nijibox
    url: https://www.nijibox.jp/?utm_source=stateofcss&utm_medium=website&utm_campaign=stateofcss2022
    imageUrl: https://devographics.github.io/surveys/state_of_css/css2022/images/sponsors/nijibox.svg
  - name: Polypane
    id: polypane
    url: https://polypane.app/
    imageUrl: https://devographics.github.io/surveys/state_of_css/css2022/images/sponsors/polypane.png

tshirt:
  images: ["shirt-mockup.jpg", "css2021-tshirt.png", "shirt-lean.jpg"]
  url: https://cottonbureau.com/products/css-retro-vhs
  price: 29
  designerUrl: https://chriskirknielsen.com/

sources:
  [
    "state_of_css_survey",
    "kevin_j_powell",
    "youtube",
    "twitter",
    "work",
    "miguel_angel_duran",
    "web_standards_ru",
    "podcast",
    "mastodon",
    "frontend_focus",
    "word_of_mouth",
    "other_online_sources",
    "state_of_js_survey",
    "codrops",
    "slack",
    "css_weekly",
    "blog",
    "sidebar",
    "telegram",
    "josh_comeau",
  ]
