surveyId: js2021
id: js2021
startedAt: January 1, 2022
endedAt: January 31, 2022
questionsUrl: https://survey.devographics.com/survey/state-of-js/2021
resultsUrl: https://2021.stateofjs.com/
year: 2021
status: 3 # preview/open/closed
resultsStatus: 3 # hidden/preview/published
# imageUrl: https://static.devographics.com/stateofjs/2021/images/stateofjs2021.png
imageUrl: https://devographics.github.io/surveys/state_of_js/js2021/images/js2021.png
faviconUrl: https://devographics.github.io/surveys/state_of_js/js2021/images/js2021-favicon.svg
socialImageUrl: https://devographics.github.io/surveys/state_of_js/js2021/images/js2021-og.png

tags:
  - js

colors:
  primary: rgb(71, 207, 237)
  secondary: "#8D4CA8"
  text: rgb(255, 246, 230)
  background: rgb(39, 35, 37)
  backgroundSecondary: rgb(48, 52, 53)

credits:
  - id: christopher_kirk_nielsen
    role: logo_design
  - id: shawn_wang
    role: survey_design
  - id: mark_erikson
    role: survey_design

translationContexts:
  [
    common,
    results,
    state_of_js,
    state_of_js_2021,
    state_of_js_2021_results,
    how_to_help,
  ]
socialMediaimageUrl: social/js2021-social.png
siteContext: stateofjs
surveySlug: js2021
siteTitle: The State of JS 2021
siteUrl: https://2021.stateofjs.com
emailOctopusUrl: https://emailoctopus.com/lists/ed0386c4-2f55-11e9-a3c9-06b79b628af2/members/embedded/1.3/add
emailOctopusSiteKey: 6LdYsmsUAAAAAPXVTt-ovRsPIJ_IVhvYBBhGvRV6
emailOctopusCode: hpc4b27b6e-eb38-11e9-be00-06b4694bee2a
translationLink: https://github.com/StateOfJS/locale-en-US
capturesUrl: https://stateofx-images.netlify.app/captures/js2021
discordUrl: https://discord.gg/zRDb35jfrt
issuesUrl: https://github.com/StateOfJS/Monorepo

tshirtImages: ["js2021-tshirt.jpg"]
tshirtLink: https://cottonbureau.com/products/javascript-retro-vhs
tshirtPrice: 29
tshirtDesignerLink: https://chriskirknielsen.com/

sponsors:
  - name: Frontend Masters
    id: frontendmasters
    url: https://frontendmasters.com/
    imageUrl: https://devographics.github.io/surveys/state_of_js/js2021/images/sponsors/frontend-masters-dark.png
  - name: Polypane
    id: polypane
    url: https://polypane.app/
    imageUrl: https://devographics.github.io/surveys/state_of_js/js2021/images/sponsors/polypane.png
  - name: Google Chrome
    id: google_chrome
    url: https://www.google.com/chrome/
    imageUrl: https://devographics.github.io/surveys/state_of_js/js2021/images/sponsors/google.png

sources:
  - id: "twitter"
  - id: "stateofjs"
  - id: "google"
  - id: "stateofcss"
  - id: "angular_community"
  - id: "ionic_community"
  - id: "work"
  - id: "js_weekly"
  - id: "reddit"
  - id: "word_of_mouth"
  - id: "slack"
  - id: "web_standards_ru"
  - id: "linkedin"
  - id: "facebook"
  - id: "telegram"
  - id: "duckduckgo"
  - id: "bytes"
  - id: "discord"
  - id: "capacitor_community"
  - id: "evan_you"
