id: state_of_graphql
slug: state_of_graphql
hashtag: StateOfGraphQL
domain: stateofgraphql.com
name: State of GraphQL

imageUrl: https://assets.devographics.com/surveys/state_of_graphql.png
faviconUrl: https://assets.devographics.com/surveys/state_of_graphql-favicon.svg

# emailOctopus:
#   listId: 3fb96da2-e6d5-11ec-9258-0241b9615763
# new list: just use state of js list
emailOctopus:
  listId: 463dc2a9-b2ff-11e8-a3c9-06b79b628af2
  submitUrl: https://eomail3.com/form/8d2b231c-47f2-11ef-9cca-cbebfc926a4c

tags:
  - graphql

partners:
  - name: Nijibox
    id: nijibox
    url: https://www.nijibox.jp/
    imageUrl: https://devographics.github.io/surveys/state_of_graphql/graphql2022/images/sponsors/nijibox.svg
