id: css2024 # used as first part of field names
surveyId: css2024 # used as first part of field names
startedAt: August 17, 2024
endedAt: September 12, 2024
questionsUrl: https://survey.devographics.com/survey/state-of-css/2024
resultsUrl: https://2024.stateofcss.com/
year: 2024
status: 3 # preview/open/closed/hidden
resultsStatus: 1 # hidden/preview/published
imageUrl: https://devographics.github.io/surveys/state_of_css/css2024/images/css2024.png
faviconUrl: https://devographics.github.io/surveys/state_of_css/css2024/images/css2024-favicon.svg
socialImageUrl: https://devographics.github.io/surveys/state_of_css/css2024/images/css2024-og.png

enableChartSponsorships: false
enableReadingList: true
enableSkip: true

colors:
  primary: rgb(239, 78, 136)
  secondary: "#3633B7"
  text: rgb(255, 246, 230)
  background: rgb(39, 35, 37)
  backgroundSecondary: rgb(62, 48, 54)

credits:
  # - id: chen_hui_jing
  #   role: survey_design
  - id: christopher_kirk_nielsen
    role: logo_design

faq:
  - how_long_will_survey_take_css2024
  - who_should_take_survey_css
  - survey_goals_css
  - data_used_css
  - results_released_css2024
  - team
  - survey_design_css2024
  # - questions_required
  - learn_more_css2024

tags:
  - css

# partners:
#   - name: Nijibox
#     id: nijibox
#     url: https://www.nijibox.jp/
#     imageUrl: https://devographics.github.io/surveys/state_of_css/css2022/images/sponsors/nijibox.svg

sponsors:
  - name: Google Chrome
    id: google_chrome
    url: https://www.google.com/chrome/?utm_source=stateofcss&utm_medium=website&utm_campaign=css2024
    imageUrl: https://devographics.github.io/surveys/state_of_css/css2024/images/sponsors/google.png
  - name: Frontend Masters
    id: frontendmasters
    url: https://frontendmasters.com/?utm_source=stateofcss&utm_medium=website&utm_campaign=css2024
    imageUrl: https://devographics.github.io/surveys/state_of_css/css2024/images/sponsors/frontend-masters-dark.png
  - name: RenderATL
    id: renderatl
    url: https://www.renderatl.com/?utm_source=stateofcss&utm_medium=website&utm_campaign=css2024
    imageUrl: https://devographics.github.io/surveys/state_of_css/css2024/images/sponsors/renderatl.png
  # - name: Nijibox
  #   id: nijibox
  #   url: https://www.nijibox.jp/?utm_source=stateofcss&utm_medium=website&utm_campaign=css2024
  #   imageUrl: https://devographics.github.io/surveys/state_of_css/css2022/images/sponsors/nijibox.svg
  - name: Polypane
    id: polypane
    url: https://polypane.app/?utm_source=stateofcss&utm_medium=website&utm_campaign=css2024
    imageUrl: https://devographics.github.io/surveys/state_of_css/css2024/images/sponsors/polypane.png

tshirt:
  images: ["shirt-mockup.jpg", "css2021-tshirt.png", "shirt-lean.jpg"]
  url: https://cottonbureau.com/products/css-retro-vhs
  price: 32
  designerUrl: https://chriskirknielsen.com/

sources:
  - id: "state_of_css_survey"
  - id: "kevin_j_powell"
  - id: "twitter"
  - id: "mastodon"
  - id: "work"
  - id: "web_dev"
  - id: "youtube"
  - id: "daily_dev"
  - id: "css_weekly"
  - id: "state_of_js_survey"
  - id: "web_standards_ru"
  - id: "frontend_focus"
  - id: "miguel_angel_duran"
  - id: "google"
  - id: "other_online_sources"
  - id: "microsoft_teams"
  - id: "word_of_mouth"
  - id: "css_tricks"
  - id: "slack"
  - id: "linkedin"
