slug: demo_survey
hashtag: StateOfGraphQL
domain: stateofgraphql.com
name: Demo survey

emailOctopus:
  listId: 3fb96da2-e6d5-11ec-9258-0241b9615763

tags:
  - graphql

partners:
  - name: Devographics
    id: devographics
    url: https://www.devographics.com/
